bot:
  # Токен бота, можно получить у @BotFather
  token: ""

db:
  # Строка подключения к базе данных.
  # Ниже заполненный пример, если используете Docker Compose файл из каталога
#  dsn: "postgresql+psycopg://superuser:superpassword@127.0.0.1/data"
#  dsn: "postgresql+psycopg://taxibot:test@127.0.0.1/taxibotdb"
  dsn: "postgresql+asyncpg://postgres:postgres@localhost/taxi_tg"
#  dsn: "postgresql+asyncpg://taxibot:test@147.45.102.183/taxibotdb"
  # Если указать "yes", то при создании движка параметр "echo" будет True,
  # что приведёт к выводу на экран расширенной информации о взаимодействии
  # SQLAlchemy и базы данных. В противном случае укажите "no"
  is_echo: "yes"